apiVersion: v1
kind: Secret
metadata:
  name: dadcloudpostgres
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  dadcloudusername: {{ .Values.dadcloudsql.username | b64enc }}
  dadcloudpassword: {{ .Values.dadcloudsql.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: site-cert
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
