apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: nextcloud-pvc
    namespace: web
  iscsi:
    chapAuthSession: false
    chapAuthDiscovery: false
    targetPortal: 192.168.137.3:3260
    iqn: 'iqn.2000-01.com.synology:drive.Nextcloud.402fcc5ed94'
    lun: 01
    fsType: 'ext4'
    readOnly: false
#    initiatorName: iqn.1993-08.org.debian:01:96d8b2647d
#  nfs:
#    server: 192.168.137.3
#    path: "/volume1/NextCloud"
#  mountOptions:
#    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: web
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  volumeName: "nextcloud-pv"