- name: Install NextCloud as Dadcloud
  hosts: controlplane
  vars_files:
    files/vault.yaml
  vars:
    namespace: web
    database: dadcloud
    databaseuser: dadcloud
    dbhost: 192.168.137.72
    dadcloudip: 192.168.137.79
    helmcommand: upgrade -i

  tasks:
    - name: Install Openshift Python Library
      command: pip3 install openshift

    - name: Install Ansible
      become: true
      apt:
        name: ansible
        state: present
        update_cache: yes

    - name: Install Ansible Galaxy Kubernetes
      command: ansible-galaxy collection install community.kubernetes
      delegate_to: localhost

    - name: Create namespace
      community.kubernetes.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: namespace
        state: present

    - name: Copy Customization
      copy:
        src: ../nextcloud-values.yaml
        dest: /tmp/

    - name: Copy Secrets
      copy:
        src: ../dadcloud-required
        dest: /tmp/

    - name: Install NextCloud repos
      community.kubernetes.helm_repository:
        name: nextcloud
        repo_url: "https://nextcloud.github.io/helm/"

    - name: Update helm repos
      command: helm repo update

    - name: Add nextcloud database
      community.general.postgresql_db:
        login_host: '{{ dbhost }}'
        login_password: '{{ postgrespassword }}'
        name: '{{ database }}'

    - name: Add nextcloud database user
      community.general.postgresql_user:
        login_host: '{{ dbhost }}'
        login_password: '{{ postgrespassword }}'
        db: '{{ database }}'
        name: '{{ databaseuser }}'
        password: '{{ dadcloudpostgrespassword }}'
        priv: ALL

    - name: Apply DadCloud Secrets
      command: >
        helm upgrade -i -n '{{ namespace }}' nextcloud-secrets /tmp/dadcloud-required
        --set dadcloudsql.username='{{ databaseuser }}'
        --set dadcloudsql.password='{{ dadcloudpostgrespassword }}'
        --set dadcloud.namespace='{{ namespace }}'

    - name: Apply NextCloud chart
      command: >
        helm upgrade -i -n {{ namespace }} nextcloud nextcloud/nextcloud -f /tmp/nextcloud-values.yaml
        --set nextcloud.password='{{ dadcloudadminpassword }}'
        --set externalDatabase.user='{{ databaseuser }}'
        --set externalDatabase.database='{{ database }}'
        --set externalDatabase.host='{{ dbhost }}'
        --set service.loadBalancerIP='{{ dadcloudip }}'