- name: Uninstall Nextcloud
  hosts: controlplane
  vars_files:
    files/vault.yaml
  vars:
    namespace: web
    database: dadcloud
    dbhost: 192.168.137.72

  tasks:
    - name: Install Openshift Python Library
      command: pip3 install openshift

    - name: Install Ansible Galaxy Kubernetes
      command: ansible-galaxy collection install community.kubernetes
      delegate_to: localhost

    - name: Remove DadCloud Secrets
      command: helm uninstall -n '{{ namespace }}' nextcloud-secrets

    - name: Remove Nextcloud
      command: helm uninstall -n {{ namespace }} nextcloud

    - name: Remove nextcloud database
      community.general.postgresql_db:
        login_host: '{{ dbhost }}'
        login_password: '{{ postgrespassword }}'
        name: '{{ database }}'
        state: absent
